In [11]:
import polars as pl

df = pl.scan_parquet('../dataset/final_train_data/merged_train_data.parquet')

In [13]:
numeric_cols = df.select(pl.col(pl.Float32, pl.Float64, pl.Int32, pl.Int16, pl.Int8)).columns
numeric_cols = [c for c in numeric_cols if c not in ['customer_ID', 'target']]

cleaned_data = df.with_columns([
    pl.col(numeric_cols).fill_null(-999)
])


cleaned_data = cleaned_data.with_columns([
    pl.col("S_2").fill_null(pl.date(1900, 1, 1))
])

C:\Users\HP\AppData\Local\Temp\ipykernel_1748\415172586.py:1: PerformanceWarning: Determining the column names of a LazyFrame requires resolving its schema, which is a potentially expensive operation. Use `LazyFrame.collect_schema().names()` to get the column names without this warning.
  numeric_cols = df.select(pl.col(pl.Float32, pl.Float64, pl.Int32, pl.Int16, pl.Int8)).columns

In [14]:
all_features = [c for c in cleaned_data.columns if c not in ["customer_ID","target","S_2"]]
volatility_exprs = [
    *[pl.col(c).mean().alias(f"{c}_mean") for c in all_features],
    *[pl.col(c).last().alias(f"{c}_last") for c in all_features],
    *[pl.col(c).std().alias(f"{c}_std") for c in all_features],  
    *[(pl.col(c).mean() - pl.col(c).last()).alias(f"{c}_delta") for c in all_features],
]


volatility_df = (
    cleaned_data.lazy()
    .group_by(["customer_ID","target"])
    .agg(volatility_exprs)
    .collect(streaming = True)
)

volatility_df.write_parquet("volatility_data.parquet")

C:\Users\HP\AppData\Local\Temp\ipykernel_1748\2123691541.py:1: PerformanceWarning: Determining the column names of a LazyFrame requires resolving its schema, which is a potentially expensive operation. Use `LazyFrame.collect_schema().names()` to get the column names without this warning.
  all_features = [c for c in cleaned_data.columns if c not in ["customer_ID","target","S_2"]]
C:\Users\HP\AppData\Local\Temp\ipykernel_1748\2123691541.py:14: DeprecationWarning: the `streaming` parameter was deprecated in 1.25.0; use `engine` instead.
  .collect(streaming = True)

In [20]:
print(volatility_df.collect_schema())

Schema({'customer_ID': String, 'target': Int64, 'P_2_mean': Float32, 'D_39_mean': Float64, 'B_1_mean': Float32, 'B_2_mean': Float32, 'R_1_mean': Float32, 'S_3_mean': Float32, 'D_41_mean': Float32, 'B_3_mean': Float32, 'D_42_mean': Float32, 'D_43_mean': Float32, 'D_44_mean': Float64, 'B_4_mean': Float64, 'D_45_mean': Float32, 'B_5_mean': Float32, 'R_2_mean': Float64, 'D_46_mean': Float32, 'D_47_mean': Float32, 'D_48_mean': Float32, 'D_49_mean': Float64, 'B_6_mean': Float32, 'B_7_mean': Float32, 'B_8_mean': Float32, 'D_50_mean': Float32, 'D_51_mean': Float64, 'B_9_mean': Float32, 'R_3_mean': Float64, 'D_52_mean': Float32, 'P_3_mean': Float32, 'B_10_mean': Float32, 'D_53_mean': Float32, 'S_5_mean': Float32, 'B_11_mean': Float32, 'S_6_mean': Float64, 'D_54_mean': Float32, 'R_4_mean': Float64, 'S_7_mean': Float32, 'B_12_mean': Float32, 'S_8_mean': Float64, 'D_55_mean': Float32, 'D_56_mean': Float32, 'B_13_mean': Float32, 'R_5_mean': Float64, 'D_58_mean': Float32, 'S_9_mean': Float32, 'B_14_mean': Float32, 'D_59_mean': Float64, 'D_60_mean': Float32, 'D_61_mean': Float32, 'B_15_mean': Float32, 'S_11_mean': Float64, 'D_62_mean': Float32, 'D_63_mean': Float64, 'D_64_mean': Float64, 'D_65_mean': Float64, 'B_16_mean': Float64, 'B_17_mean': Float32, 'B_18_mean': Float32, 'B_19_mean': Float64, 'D_66_mean': Float64, 'B_20_mean': Float64, 'D_68_mean': Float64, 'S_12_mean': Float32, 'R_6_mean': Float32, 'S_13_mean': Float64, 'B_21_mean': Float32, 'D_69_mean': Float32, 'B_22_mean': Float64, 'D_70_mean': Float64, 'D_71_mean': Float32, 'D_72_mean': Float64, 'S_15_mean': Float64, 'B_23_mean': Float32, 'D_73_mean': Float32, 'P_4_mean': Float32, 'D_74_mean': Float64, 'D_75_mean': Float64, 'D_76_mean': Float32, 'B_24_mean': Float32, 'R_7_mean': Float32, 'D_77_mean': Float32, 'B_25_mean': Float32, 'B_26_mean': Float32, 'D_78_mean': Float64, 'D_79_mean': Float64, 'R_8_mean': Float64, 'R_9_mean': Float64, 'S_16_mean': Float32, 'D_80_mean': Float64, 'R_10_mean': Float64, 'R_11_mean': Float64, 'B_27_mean': Float32, 'D_81_mean': Float64, 'D_82_mean': Float64, 'S_17_mean': Float32, 'R_12_mean': Float32, 'B_28_mean': Float32, 'R_13_mean': Float64, 'D_83_mean': Float64, 'R_14_mean': Float32, 'R_15_mean': Float64, 'D_84_mean': Float64, 'R_16_mean': Float64, 'B_29_mean': Float32, 'B_30_mean': Float64, 'S_18_mean': Float64, 'D_86_mean': Float64, 'D_87_mean': Float64, 'R_17_mean': Float64, 'R_18_mean': Float64, 'D_88_mean': Float32, 'B_31_mean': Float64, 'S_19_mean': Float32, 'R_19_mean': Float64, 'B_32_mean': Float64, 'S_20_mean': Float64, 'R_20_mean': Float64, 'R_21_mean': Float64, 'B_33_mean': Float64, 'D_89_mean': Float64, 'R_22_mean': Float64, 'R_23_mean': Float64, 'D_91_mean': Float64, 'D_92_mean': Float64, 'D_93_mean': Float64, 'D_94_mean': Float64, 'R_24_mean': Float64, 'R_25_mean': Float64, 'D_96_mean': Float64, 'S_22_mean': Float32, 'S_23_mean': Float32, 'S_24_mean': Float32, 'S_25_mean': Float32, 'S_26_mean': Float32, 'D_102_mean': Float32, 'D_103_mean': Float64, 'D_104_mean': Float32, 'D_105_mean': Float32, 'D_106_mean': Float64, 'D_107_mean': Float64, 'B_36_mean': Float32, 'B_37_mean': Float32, 'R_26_mean': Float64, 'R_27_mean': Float32, 'B_38_mean': Float64, 'D_108_mean': Float64, 'D_109_mean': Float64, 'D_110_mean': Float32, 'D_111_mean': Float64, 'B_39_mean': Float32, 'D_112_mean': Float32, 'B_40_mean': Float32, 'S_27_mean': Float32, 'D_113_mean': Float64, 'D_114_mean': Float64, 'D_115_mean': Float32, 'D_116_mean': Float64, 'D_117_mean': Float64, 'D_118_mean': Float32, 'D_119_mean': Float32, 'D_120_mean': Float64, 'D_121_mean': Float32, 'D_122_mean': Float64, 'D_123_mean': Float64, 'D_124_mean': Float64, 'D_125_mean': Float64, 'D_126_mean': Float64, 'D_127_mean': Float64, 'D_128_mean': Float32, 'D_129_mean': Float64, 'B_41_mean': Float64, 'B_42_mean': Float32, 'D_130_mean': Float32, 'D_131_mean': Float32, 'D_132_mean': Float32, 'D_133_mean': Float32, 'R_28_mean': Float64, 'D_134_mean': Float32, 'D_135_mean': Float64, 'D_136_mean': Float64, 'D_137_mean': Float64, 'D_138_mean': Float64, 'D_139_mean': Float64, 'D_140_mean': Float64, 'D_141_mean': Float32, 'D_142_mean': Float32, 'D_143_mean': Float64, 'D_144_mean': Float32, 'D_145_mean': Float64, 'P_2_last': Float32, 'D_39_last': Int16, 'B_1_last': Float32, 'B_2_last': Float32, 'R_1_last': Float32, 'S_3_last': Float32, 'D_41_last': Float32, 'B_3_last': Float32, 'D_42_last': Float32, 'D_43_last': Float32, 'D_44_last': Int16, 'B_4_last': Int16, 'D_45_last': Float32, 'B_5_last': Float32, 'R_2_last': Int16, 'D_46_last': Float32, 'D_47_last': Float32, 'D_48_last': Float32, 'D_49_last': Int16, 'B_6_last': Float32, 'B_7_last': Float32, 'B_8_last': Float32, 'D_50_last': Float32, 'D_51_last': Int16, 'B_9_last': Float32, 'R_3_last': Int16, 'D_52_last': Float32, 'P_3_last': Float32, 'B_10_last': Float32, 'D_53_last': Float32, 'S_5_last': Float32, 'B_11_last': Float32, 'S_6_last': Int16, 'D_54_last': Float32, 'R_4_last': Int16, 'S_7_last': Float32, 'B_12_last': Float32, 'S_8_last': Int16, 'D_55_last': Float32, 'D_56_last': Float32, 'B_13_last': Float32, 'R_5_last': Int16, 'D_58_last': Float32, 'S_9_last': Float32, 'B_14_last': Float32, 'D_59_last': Int16, 'D_60_last': Float32, 'D_61_last': Float32, 'B_15_last': Float32, 'S_11_last': Int16, 'D_62_last': Float32, 'D_63_last': Int16, 'D_64_last': Int16, 'D_65_last': Int16, 'B_16_last': Int16, 'B_17_last': Float32, 'B_18_last': Float32, 'B_19_last': Int16, 'D_66_last': Int16, 'B_20_last': Int16, 'D_68_last': Int16, 'S_12_last': Float32, 'R_6_last': Float32, 'S_13_last': Int16, 'B_21_last': Float32, 'D_69_last': Float32, 'B_22_last': Int16, 'D_70_last': Int16, 'D_71_last': Float32, 'D_72_last': Int16, 'S_15_last': Int16, 'B_23_last': Float32, 'D_73_last': Float32, 'P_4_last': Float32, 'D_74_last': Int16, 'D_75_last': Int16, 'D_76_last': Float32, 'B_24_last': Float32, 'R_7_last': Float32, 'D_77_last': Float32, 'B_25_last': Float32, 'B_26_last': Float32, 'D_78_last': Int16, 'D_79_last': Int16, 'R_8_last': Int16, 'R_9_last': Int16, 'S_16_last': Float32, 'D_80_last': Int16, 'R_10_last': Int16, 'R_11_last': Int16, 'B_27_last': Float32, 'D_81_last': Int16, 'D_82_last': Int16, 'S_17_last': Float32, 'R_12_last': Float32, 'B_28_last': Float32, 'R_13_last': Int16, 'D_83_last': Int16, 'R_14_last': Float32, 'R_15_last': Int16, 'D_84_last': Int16, 'R_16_last': Int16, 'B_29_last': Float32, 'B_30_last': Int16, 'S_18_last': Int16, 'D_86_last': Int16, 'D_87_last': Int16, 'R_17_last': Int16, 'R_18_last': Int16, 'D_88_last': Float32, 'B_31_last': Int16, 'S_19_last': Float32, 'R_19_last': Int16, 'B_32_last': Int16, 'S_20_last': Int16, 'R_20_last': Int16, 'R_21_last': Int16, 'B_33_last': Int16, 'D_89_last': Int16, 'R_22_last': Int16, 'R_23_last': Int16, 'D_91_last': Int16, 'D_92_last': Int16, 'D_93_last': Int16, 'D_94_last': Int16, 'R_24_last': Int16, 'R_25_last': Int16, 'D_96_last': Int16, 'S_22_last': Float32, 'S_23_last': Float32, 'S_24_last': Float32, 'S_25_last': Float32, 'S_26_last': Float32, 'D_102_last': Float32, 'D_103_last': Int16, 'D_104_last': Float32, 'D_105_last': Float32, 'D_106_last': Int16, 'D_107_last': Int16, 'B_36_last': Float32, 'B_37_last': Float32, 'R_26_last': Int16, 'R_27_last': Float32, 'B_38_last': Int16, 'D_108_last': Int16, 'D_109_last': Int16, 'D_110_last': Float32, 'D_111_last': Int16, 'B_39_last': Float32, 'D_112_last': Float32, 'B_40_last': Float32, 'S_27_last': Float32, 'D_113_last': Int16, 'D_114_last': Int16, 'D_115_last': Float32, 'D_116_last': Int16, 'D_117_last': Int16, 'D_118_last': Float32, 'D_119_last': Float32, 'D_120_last': Int16, 'D_121_last': Float32, 'D_122_last': Int16, 'D_123_last': Int16, 'D_124_last': Int16, 'D_125_last': Int16, 'D_126_last': Int16, 'D_127_last': Int16, 'D_128_last': Float32, 'D_129_last': Int16, 'B_41_last': Int16, 'B_42_last': Float32, 'D_130_last': Float32, 'D_131_last': Float32, 'D_132_last': Float32, 'D_133_last': Float32, 'R_28_last': Int16, 'D_134_last': Float32, 'D_135_last': Int16, 'D_136_last': Int16, 'D_137_last': Int16, 'D_138_last': Int16, 'D_139_last': Int16, 'D_140_last': Int16, 'D_141_last': Float32, 'D_142_last': Float32, 'D_143_last': Int16, 'D_144_last': Float32, 'D_145_last': Int16, 'P_2_std': Float32, 'D_39_std': Float64, 'B_1_std': Float32, 'B_2_std': Float32, 'R_1_std': Float32, 'S_3_std': Float32, 'D_41_std': Float32, 'B_3_std': Float32, 'D_42_std': Float32, 'D_43_std': Float32, 'D_44_std': Float64, 'B_4_std': Float64, 'D_45_std': Float32, 'B_5_std': Float32, 'R_2_std': Float64, 'D_46_std': Float32, 'D_47_std': Float32, 'D_48_std': Float32, 'D_49_std': Float64, 'B_6_std': Float32, 'B_7_std': Float32, 'B_8_std': Float32, 'D_50_std': Float32, 'D_51_std': Float64, 'B_9_std': Float32, 'R_3_std': Float64, 'D_52_std': Float32, 'P_3_std': Float32, 'B_10_std': Float32, 'D_53_std': Float32, 'S_5_std': Float32, 'B_11_std': Float32, 'S_6_std': Float64, 'D_54_std': Float32, 'R_4_std': Float64, 'S_7_std': Float32, 'B_12_std': Float32, 'S_8_std': Float64, 'D_55_std': Float32, 'D_56_std': Float32, 'B_13_std': Float32, 'R_5_std': Float64, 'D_58_std': Float32, 'S_9_std': Float32, 'B_14_std': Float32, 'D_59_std': Float64, 'D_60_std': Float32, 'D_61_std': Float32, 'B_15_std': Float32, 'S_11_std': Float64, 'D_62_std': Float32, 'D_63_std': Float64, 'D_64_std': Float64, 'D_65_std': Float64, 'B_16_std': Float64, 'B_17_std': Float32, 'B_18_std': Float32, 'B_19_std': Float64, 'D_66_std': Float64, 'B_20_std': Float64, 'D_68_std': Float64, 'S_12_std': Float32, 'R_6_std': Float32, 'S_13_std': Float64, 'B_21_std': Float32, 'D_69_std': Float32, 'B_22_std': Float64, 'D_70_std': Float64, 'D_71_std': Float32, 'D_72_std': Float64, 'S_15_std': Float64, 'B_23_std': Float32, 'D_73_std': Float32, 'P_4_std': Float32, 'D_74_std': Float64, 'D_75_std': Float64, 'D_76_std': Float32, 'B_24_std': Float32, 'R_7_std': Float32, 'D_77_std': Float32, 'B_25_std': Float32, 'B_26_std': Float32, 'D_78_std': Float64, 'D_79_std': Float64, 'R_8_std': Float64, 'R_9_std': Float64, 'S_16_std': Float32, 'D_80_std': Float64, 'R_10_std': Float64, 'R_11_std': Float64, 'B_27_std': Float32, 'D_81_std': Float64, 'D_82_std': Float64, 'S_17_std': Float32, 'R_12_std': Float32, 'B_28_std': Float32, 'R_13_std': Float64, 'D_83_std': Float64, 'R_14_std': Float32, 'R_15_std': Float64, 'D_84_std': Float64, 'R_16_std': Float64, 'B_29_std': Float32, 'B_30_std': Float64, 'S_18_std': Float64, 'D_86_std': Float64, 'D_87_std': Float64, 'R_17_std': Float64, 'R_18_std': Float64, 'D_88_std': Float32, 'B_31_std': Float64, 'S_19_std': Float32, 'R_19_std': Float64, 'B_32_std': Float64, 'S_20_std': Float64, 'R_20_std': Float64, 'R_21_std': Float64, 'B_33_std': Float64, 'D_89_std': Float64, 'R_22_std': Float64, 'R_23_std': Float64, 'D_91_std': Float64, 'D_92_std': Float64, 'D_93_std': Float64, 'D_94_std': Float64, 'R_24_std': Float64, 'R_25_std': Float64, 'D_96_std': Float64, 'S_22_std': Float32, 'S_23_std': Float32, 'S_24_std': Float32, 'S_25_std': Float32, 'S_26_std': Float32, 'D_102_std': Float32, 'D_103_std': Float64, 'D_104_std': Float32, 'D_105_std': Float32, 'D_106_std': Float64, 'D_107_std': Float64, 'B_36_std': Float32, 'B_37_std': Float32, 'R_26_std': Float64, 'R_27_std': Float32, 'B_38_std': Float64, 'D_108_std': Float64, 'D_109_std': Float64, 'D_110_std': Float32, 'D_111_std': Float64, 'B_39_std': Float32, 'D_112_std': Float32, 'B_40_std': Float32, 'S_27_std': Float32, 'D_113_std': Float64, 'D_114_std': Float64, 'D_115_std': Float32, 'D_116_std': Float64, 'D_117_std': Float64, 'D_118_std': Float32, 'D_119_std': Float32, 'D_120_std': Float64, 'D_121_std': Float32, 'D_122_std': Float64, 'D_123_std': Float64, 'D_124_std': Float64, 'D_125_std': Float64, 'D_126_std': Float64, 'D_127_std': Float64, 'D_128_std': Float32, 'D_129_std': Float64, 'B_41_std': Float64, 'B_42_std': Float32, 'D_130_std': Float32, 'D_131_std': Float32, 'D_132_std': Float32, 'D_133_std': Float32, 'R_28_std': Float64, 'D_134_std': Float32, 'D_135_std': Float64, 'D_136_std': Float64, 'D_137_std': Float64, 'D_138_std': Float64, 'D_139_std': Float64, 'D_140_std': Float64, 'D_141_std': Float32, 'D_142_std': Float32, 'D_143_std': Float64, 'D_144_std': Float32, 'D_145_std': Float64, 'P_2_delta': Float32, 'D_39_delta': Float64, 'B_1_delta': Float32, 'B_2_delta': Float32, 'R_1_delta': Float32, 'S_3_delta': Float32, 'D_41_delta': Float32, 'B_3_delta': Float32, 'D_42_delta': Float32, 'D_43_delta': Float32, 'D_44_delta': Float64, 'B_4_delta': Float64, 'D_45_delta': Float32, 'B_5_delta': Float32, 'R_2_delta': Float64, 'D_46_delta': Float32, 'D_47_delta': Float32, 'D_48_delta': Float32, 'D_49_delta': Float64, 'B_6_delta': Float32, 'B_7_delta': Float32, 'B_8_delta': Float32, 'D_50_delta': Float32, 'D_51_delta': Float64, 'B_9_delta': Float32, 'R_3_delta': Float64, 'D_52_delta': Float32, 'P_3_delta': Float32, 'B_10_delta': Float32, 'D_53_delta': Float32, 'S_5_delta': Float32, 'B_11_delta': Float32, 'S_6_delta': Float64, 'D_54_delta': Float32, 'R_4_delta': Float64, 'S_7_delta': Float32, 'B_12_delta': Float32, 'S_8_delta': Float64, 'D_55_delta': Float32, 'D_56_delta': Float32, 'B_13_delta': Float32, 'R_5_delta': Float64, 'D_58_delta': Float32, 'S_9_delta': Float32, 'B_14_delta': Float32, 'D_59_delta': Float64, 'D_60_delta': Float32, 'D_61_delta': Float32, 'B_15_delta': Float32, 'S_11_delta': Float64, 'D_62_delta': Float32, 'D_63_delta': Float64, 'D_64_delta': Float64, 'D_65_delta': Float64, 'B_16_delta': Float64, 'B_17_delta': Float32, 'B_18_delta': Float32, 'B_19_delta': Float64, 'D_66_delta': Float64, 'B_20_delta': Float64, 'D_68_delta': Float64, 'S_12_delta': Float32, 'R_6_delta': Float32, 'S_13_delta': Float64, 'B_21_delta': Float32, 'D_69_delta': Float32, 'B_22_delta': Float64, 'D_70_delta': Float64, 'D_71_delta': Float32, 'D_72_delta': Float64, 'S_15_delta': Float64, 'B_23_delta': Float32, 'D_73_delta': Float32, 'P_4_delta': Float32, 'D_74_delta': Float64, 'D_75_delta': Float64, 'D_76_delta': Float32, 'B_24_delta': Float32, 'R_7_delta': Float32, 'D_77_delta': Float32, 'B_25_delta': Float32, 'B_26_delta': Float32, 'D_78_delta': Float64, 'D_79_delta': Float64, 'R_8_delta': Float64, 'R_9_delta': Float64, 'S_16_delta': Float32, 'D_80_delta': Float64, 'R_10_delta': Float64, 'R_11_delta': Float64, 'B_27_delta': Float32, 'D_81_delta': Float64, 'D_82_delta': Float64, 'S_17_delta': Float32, 'R_12_delta': Float32, 'B_28_delta': Float32, 'R_13_delta': Float64, 'D_83_delta': Float64, 'R_14_delta': Float32, 'R_15_delta': Float64, 'D_84_delta': Float64, 'R_16_delta': Float64, 'B_29_delta': Float32, 'B_30_delta': Float64, 'S_18_delta': Float64, 'D_86_delta': Float64, 'D_87_delta': Float64, 'R_17_delta': Float64, 'R_18_delta': Float64, 'D_88_delta': Float32, 'B_31_delta': Float64, 'S_19_delta': Float32, 'R_19_delta': Float64, 'B_32_delta': Float64, 'S_20_delta': Float64, 'R_20_delta': Float64, 'R_21_delta': Float64, 'B_33_delta': Float64, 'D_89_delta': Float64, 'R_22_delta': Float64, 'R_23_delta': Float64, 'D_91_delta': Float64, 'D_92_delta': Float64, 'D_93_delta': Float64, 'D_94_delta': Float64, 'R_24_delta': Float64, 'R_25_delta': Float64, 'D_96_delta': Float64, 'S_22_delta': Float32, 'S_23_delta': Float32, 'S_24_delta': Float32, 'S_25_delta': Float32, 'S_26_delta': Float32, 'D_102_delta': Float32, 'D_103_delta': Float64, 'D_104_delta': Float32, 'D_105_delta': Float32, 'D_106_delta': Float64, 'D_107_delta': Float64, 'B_36_delta': Float32, 'B_37_delta': Float32, 'R_26_delta': Float64, 'R_27_delta': Float32, 'B_38_delta': Float64, 'D_108_delta': Float64, 'D_109_delta': Float64, 'D_110_delta': Float32, 'D_111_delta': Float64, 'B_39_delta': Float32, 'D_112_delta': Float32, 'B_40_delta': Float32, 'S_27_delta': Float32, 'D_113_delta': Float64, 'D_114_delta': Float64, 'D_115_delta': Float32, 'D_116_delta': Float64, 'D_117_delta': Float64, 'D_118_delta': Float32, 'D_119_delta': Float32, 'D_120_delta': Float64, 'D_121_delta': Float32, 'D_122_delta': Float64, 'D_123_delta': Float64, 'D_124_delta': Float64, 'D_125_delta': Float64, 'D_126_delta': Float64, 'D_127_delta': Float64, 'D_128_delta': Float32, 'D_129_delta': Float64, 'B_41_delta': Float64, 'B_42_delta': Float32, 'D_130_delta': Float32, 'D_131_delta': Float32, 'D_132_delta': Float32, 'D_133_delta': Float32, 'R_28_delta': Float64, 'D_134_delta': Float32, 'D_135_delta': Float64, 'D_136_delta': Float64, 'D_137_delta': Float64, 'D_138_delta': Float64, 'D_139_delta': Float64, 'D_140_delta': Float64, 'D_141_delta': Float32, 'D_142_delta': Float32, 'D_143_delta': Float64, 'D_144_delta': Float32, 'D_145_delta': Float64})

In [17]:
from lightgbm import LGBMClassifier

In [19]:
import pandas as pd
all_importances = []
n_iterations = 3

defaults_df = volatility_df.filter(pl.col("target") == 1)
non_defaults_df = volatility_df.filter(pl.col("target") == 0)

for i in range(n_iterations):
    print(f"Iteration {i+1}/{n_iterations}...")
    
    sample = pl.concat([
        defaults_df.sample(n=100000, seed=i),
        non_defaults_df.sample(n=100000, seed=i)
    ])
    
   
    drop_cols = ["customer_ID", "target", "S_2"]
    X = sample.drop([c for c in drop_cols if c in sample.columns]).to_pandas()
    y = sample["target"].to_pandas()
    
    if i == 0:
        constant_cols = [col for col in X.columns if X[col].nunique() <= 1]
        print(f"Dropping {len(constant_cols)} constant columns.")
    
    X = X.drop(columns=constant_cols)
    
    selector = LGBMClassifier(
        n_estimators=250, 
        importance_type='gain', 
        random_state=i,
        device="gpu"
    )
    selector.fit(X, y)
    
    imp = pd.DataFrame({'feature': X.columns, f'gain_{i}': selector.feature_importances_})
    all_importances.append(imp.set_index('feature'))


final_rank = pd.concat(all_importances, axis=1).mean(axis=1).sort_values(ascending=False)

top_features_all = final_rank.head(50)
print("\n--- Top Features (Audit) ---")
print(top_features_all.head(10))

magic_25 = final_rank.head(25).index.tolist()
print("\nFINAL MAGIC 25 LIST:")
print(magic_25)

import json
with open('magic_25_features_volatility.json', 'w') as f:
    json.dump(magic_25, f)

Iteration 1/3...
Dropping 0 constant columns.
[LightGBM] [Info] Number of positive: 100000, number of negative: 100000
[LightGBM] [Info] This is the GPU trainer!!
[LightGBM] [Info] Total Bins 142263
[LightGBM] [Info] Number of data points in the train set: 200000, number of used features: 751
[LightGBM] [Info] Using GPU Device: Intel(R) UHD Graphics, Vendor: Intel(R) Corporation
[LightGBM] [Info] Compiling OpenCL Kernel with 256 bins...
[LightGBM] [Info] GPU programs have been built
[LightGBM] [Info] Size of histogram bin entry: 8
[LightGBM] [Info] 403 dense feature groups (77.06 MB) transferred to GPU in 0.060239 secs. 1 sparse feature groups
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.500000 -> initscore=0.000000
Iteration 2/3...
[LightGBM] [Info] Number of positive: 100000, number of negative: 100000
[LightGBM] [Info] This is the GPU trainer!!
[LightGBM] [Info] Total Bins 142303
[LightGBM] [Info] Number of data points in the train set: 200000, number of used features: 752
[LightGBM] [Info] Using GPU Device: Intel(R) UHD Graphics, Vendor: Intel(R) Corporation
[LightGBM] [Info] Compiling OpenCL Kernel with 256 bins...
[LightGBM] [Info] GPU programs have been built
[LightGBM] [Info] Size of histogram bin entry: 8
[LightGBM] [Info] 403 dense feature groups (77.06 MB) transferred to GPU in 0.183383 secs. 1 sparse feature groups
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.500000 -> initscore=0.000000
Iteration 3/3...
[LightGBM] [Info] Number of positive: 100000, number of negative: 100000
[LightGBM] [Info] This is the GPU trainer!!
[LightGBM] [Info] Total Bins 142249
[LightGBM] [Info] Number of data points in the train set: 200000, number of used features: 751
[LightGBM] [Info] Using GPU Device: Intel(R) UHD Graphics, Vendor: Intel(R) Corporation
[LightGBM] [Info] Compiling OpenCL Kernel with 256 bins...
[LightGBM] [Info] GPU programs have been built
[LightGBM] [Info] Size of histogram bin entry: 8
[LightGBM] [Info] 403 dense feature groups (77.06 MB) transferred to GPU in 0.040657 secs. 1 sparse feature groups
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.500000 -> initscore=0.000000

--- Top Features (Audit) ---
feature
P_2_last     613619.814909
B_1_last      49615.806847
B_2_last      19306.749642
B_9_last      16028.478968
B_11_last     14858.158001
R_1_mean      13654.668004
S_3_last      12252.077333
R_1_last      11192.655967
D_39_last     10158.343732
D_48_last      9586.211225
dtype: float64

FINAL MAGIC 25 LIST:
['P_2_last', 'B_1_last', 'B_2_last', 'B_9_last', 'B_11_last', 'R_1_mean', 'S_3_last', 'R_1_last', 'D_39_last', 'D_48_last', 'B_4_delta', 'D_44_last', 'D_43_last', 'B_3_std', 'R_3_mean', 'R_2_last', 'D_45_mean', 'D_42_last', 'B_7_last', 'B_3_last', 'B_4_last', 'P_2_mean', 'D_50_last', 'D_51_mean', 'D_41_last']

By including Standard Deviation in our feature pool, we found that the model prioritized temporal volatility ($B\_3\_std$) over simple averages. This confirms that credit risk is not static; it is a sequence-dependent problem.

In [24]:
slope_exprs = [
    (
        (pl.col(c).last() - pl.col(c).get(pl.col(c).len() - 7)) / 6
    ).alias(f"{c}_slope")
    for c in ["P_2", "B_1", "B_3", "D_39", "S_3"]
]

slope_df = (
    cleaned_data.lazy()
    .group_by("customer_ID")
    .agg([
        pl.count().alias("row_count"),
        *slope_exprs
    ])
    .filter(pl.col("row_count") >= 7)  
    .collect()
)

C:\Users\HP\AppData\Local\Temp\ipykernel_1748\3448396050.py:12: DeprecationWarning: `pl.count()` is deprecated. Please use `pl.len()` instead.
(Deprecated in version 0.20.5)
  pl.count().alias("row_count"),

We calculated the Linear Slope of the raw 13-month sequences for our top features. We found that even when users shared identical 'Mean' and 'Last' values, the Direction of Change was a decisive factor in predicting default.

In [25]:
final_audit_df = slope_df.join(volatility_df, on="customer_ID")


recovering_cases = final_audit_df.filter(
    (pl.col("P_2_mean") < 0.3) & (pl.col("P_2_slope") > 0.05)
).head(3)


spiraling_cases = final_audit_df.filter(
    (pl.col("P_2_mean") > 0.7) & (pl.col("P_2_slope") < -0.05)
).head(3)

In [26]:
recovering_cases

shape: (3, 760)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ customer_ ┆ row_count ┆ P_2_slope ┆ B_1_slope ┆ … ┆ D_142_del ┆ D_143_del ┆ D_144_del ┆ D_145_de │
│ ID        ┆ ---       ┆ ---       ┆ ---       ┆   ┆ ta        ┆ ta        ┆ ta        ┆ lta      │
│ ---       ┆ u32       ┆ f32       ┆ f32       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---      │
│ str       ┆           ┆           ┆           ┆   ┆ f32       ┆ f64       ┆ f32       ┆ f64      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 6ec380f80 ┆ 7         ┆ 166.64210 ┆ 0.001222  ┆ … ┆ 0.0       ┆ -0.285714 ┆ -285.4314 ┆ -0.28571 │
│ c9c7f59f1 ┆           ┆ 5         ┆           ┆   ┆           ┆           ┆ 58        ┆ 4        │
│ 2b7da1bd6 ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 92c…      ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 3e2e44820 ┆ 8         ┆ 0.091488  ┆ -0.219775 ┆ … ┆ 0.0       ┆ -0.25     ┆ -124.8738 ┆ -0.25    │
│ ab5252737 ┆           ┆           ┆           ┆   ┆           ┆           ┆ 4         ┆          │
│ 584af522d ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 46c…      ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 6195e918f ┆ 7         ┆ 166.64370 ┆ 0.003522  ┆ … ┆ 0.0       ┆ -0.285714 ┆ -142.7114 ┆ -0.28571 │
│ e50a5b41e ┆           ┆ 7         ┆           ┆   ┆           ┆           ┆ 56        ┆ 4        │
│ d0782ca6e ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 986…      ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [27]:
spiraling_cases

shape: (3, 760)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ customer_ ┆ row_count ┆ P_2_slope ┆ B_1_slope ┆ … ┆ D_142_del ┆ D_143_del ┆ D_144_del ┆ D_145_de │
│ ID        ┆ ---       ┆ ---       ┆ ---       ┆   ┆ ta        ┆ ta        ┆ ta        ┆ lta      │
│ ---       ┆ u32       ┆ f32       ┆ f32       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---      │
│ str       ┆           ┆           ┆           ┆   ┆ f32       ┆ f64       ┆ f32       ┆ f64      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 6e2813eae ┆ 13        ┆ -0.064756 ┆ -0.000422 ┆ … ┆ 0.0       ┆ 0.0       ┆ 0.002085  ┆ 0.0      │
│ c3589154d ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 2764dba67 ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 5b7…      ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 6e7cc6944 ┆ 13        ┆ -0.051789 ┆ -0.0047   ┆ … ┆ 0.0       ┆ 0.0       ┆ -0.000162 ┆ 0.0      │
│ 327a9eb1e ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 94344ecf9 ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ da3…      ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ b1bc19233 ┆ 13        ┆ -0.109583 ┆ -0.00794  ┆ … ┆ 0.0       ┆ 0.0       ┆ 0.002884  ┆ 0.0      │
│ ac6790ec4 ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ db015f6a5 ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ f21…      ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

# Bold Why we calculated slope ?

We calcualted slope to understand the trend of the data over time.Because sometimes the data might be increasing or decreasing over time and we want to capture that trend.For Example: If you are standing at the edge of a cliff, are you walking toward it or away from it? The "Last" value only tells us where you are standing; the Slope tells us which way you are moving.

# Bold Why Temporal Analysis?

Consider Two users : 
1. User A: Had high debt for 10 months but got a high-paying job 3 months ago and has paid off everything since.The model wrongly rejects their loan because it's stuck in the past.
2. User B: Was a perfect "A+" customer for 11 months, but in the last 60 days, their spending has tripled and they stopped paying.The model might fail to highlight this recent change.

User A can be classified as recovered user.
User B can be classified as spiraling user.

We were able to identify these two types of users by calculating the slope of the data over time.